Repository TheLope/ClueSaver, pull requests merged in 2025-08, with the labels that each got.

#18 Clue Saver v2.1.3
  README.md
  build.gradle
  src/main/java/com/cluesaver/ClueSaverConfig.java
  src/main/java/com/cluesaver/ClueSaverOverlay.java
  src/main/java/com/cluesaver/ClueSaverPlugin.java
  src/main/java/com/cluesaver/ClueSaverUI.java
  src/main/java/com/cluesaver/ClueStates.java
  src/main/java/com/cluesaver/ids/ToaChest.java
  src/main/java/com/cluesaver/ids/TobChest.java
Labels: bug, enhancement

#22 Added UI offset & left/right configuration
  src/main/java/com/cluesaver/ClueSaverConfig.java
  src/main/java/com/cluesaver/ClueSaverUI.java
Labels: enhancement

#26 Clue Saver v2.2.0
  build.gradle
Labels: version
