Repository TheLope/ClueSaver, pull requests merged in 2025-07, with the labels that each got.

#6 feat: Clue Saver UI
  README.md
  src/main/java/com/cluesaver/ClueSaverConfig.java
  src/main/java/com/cluesaver/ClueSaverPlugin.java
  src/main/java/com/cluesaver/ClueSaverUI.java
  src/main/resources/com/cluesaver/ClosedUI.png
  src/main/resources/com/cluesaver/activeClueSaver.png
  src/main/resources/com/cluesaver/bankIcon.png
  src/main/resources/com/cluesaver/buttonUI.png
  src/main/resources/com/cluesaver/buttonUIhovered.png
  src/main/resources/com/cluesaver/cluescrollBeginner.png
  src/main/resources/com/cluesaver/cluescrollEasy.png
  src/main/resources/com/cluesaver/cluescrollElite.png
  src/main/resources/com/cluesaver/cluescrollHard.png
  src/main/resources/com/cluesaver/cluescrollMaster.png
  src/main/resources/com/cluesaver/cluescrollMedium.png
  src/main/resources/com/cluesaver/invIcon.png
  src/main/resources/com/cluesaver/pip.png
  src/main/resources/com/cluesaver/pipGreen.png
  src/main/resources/com/cluesaver/pipOrange.png
  src/main/resources/com/cluesaver/pipRed.png
Labels: enhancement

#9 feat: Ability to disable tiers
  src/main/java/com/cluesaver/ClueSaverConfig.java
  src/main/java/com/cluesaver/ClueSaverPlugin.java
  src/main/java/com/cluesaver/ClueSaverUI.java
Labels: enhancement

#11 Add Varlamore Part 3 Clues
  build.gradle
  src/main/java/com/cluesaver/ids/ClueScrolls.java
Labels: enhancement

#12 Clue UI - Minor Fixes
  src/main/java/com/cluesaver/ClueSaverUI.java
Labels: bug, enhancement

#14 fix: UI onConfigChanged
  src/main/java/com/cluesaver/ClueSaverPlugin.java
Labels: bug

#15 fix: onConfigChanged group check
  src/main/java/com/cluesaver/ClueSaverPlugin.java
Labels: bug
